### PR TITLE
Change PulpAnsibleModule into a context manager

### PR DESCRIPTION
**Pull request by mdellweg**
This is my take on how the ansible module api should have been.

### CODE REVIEW

**Comment by mdellweg** [comment]
@Timoses I'd like your :eyes: on this.

**Comment by Timoses** [comment]
Looks interesting. The `argument_spec` stuff in Pulp(Entity)AnsibleModule is great, makes it much cleaner.

I kind of thought about making all the `PulpEntity` classes independent from the module.
I guess this is a start in that `fail_json` is no longer directly called from the Entities.

Perhaps it could even go a step further?
The Entity itself could keep track of `changed` and `results`.
So instead of `self.module.set_changed()` it would be `self._changed = True` and the module would check the entity afterwards and decide upon the entity's state how to continue (e.g. exit_json with changed, or fail_json, ...)

I'm not sure how feasible this is. Plus, how much sense it makes to disentangle PulpEntity from Ansible module logic. Afterall, it's currently used in Ansible Module code. So where would be the plus side? What's the goal?

In regard to using the Modules with `with`, I'm not sure what the upside is (other than making use of the `fail_json` upon a thrown exception from within the `with` statement). Also, doesn't this make it so that the module class **must** be used with `with`? As otherwise exceptions wouldn't correctly trigger a `fail_json` call in the module?

**Comment by mdellweg** [comment]
> Looks interesting. The `argument_spec` stuff in Pulp(Entity)AnsibleModule is great, makes it much cleaner.
> 
> I kind of thought about making all the `PulpEntity` classes independent from the module.
> I guess this is a start in that `fail_json` is no longer directly called from the Entities.

I mostly did this, because i dislike the way, `fail_json` breaks out of the control flow. Exceptions are built for this. You can catch them selectively, refine them rethrow them or rescue your system.

> Perhaps it could even go a step further?
> The Entity itself could keep track of `changed` and `results`.
> So instead of `self.module.set_changed()` it would be `self._changed = True` and the module would check the entity afterwards and decide upon the entity's state how to continue (e.g. exit_json with changed, or fail_json, ...)
> 
> I'm not sure how feasible this is. Plus, how much sense it makes to disentangle PulpEntity from Ansible module logic. Afterall, it's currently used in Ansible Module code. So where would be the plus side? What's the goal?

Hmm, not immediately obvious to me. The whole bring this entity in that state is well tailored for ansible.

> In regard to using the Modules with `with`, I'm not sure what the upside is (other than automagically making use of the `fail_json` upon a thrown exception from within the `with` statement). Also, doesn't this make it so that the module class **must** be used with `with`? As otherwise exceptions wouldn't correctly trigger a `fail_json` call in the module?

That is right. But i do not see that as a big problem, as it is going to be common boilerplate code.
(`__exit__` is the closest thing in python to a destructor.)

**Comment by Timoses** [comment]
Ok, I can agree with all that you've mentioned!

lgtm :+1:

**Pull request merged**
