### PR TITLE
Make preparations to implement more pulp plugins

### PR DESCRIPTION
**Pull request by Timoses**
This PR tries to make some preparations to make the code more modular in terms of pulp plugin implementations.

Suggestions for improvements are very welcome!

(Note that this PR is based on https://github.com/mdellweg/ansible_modules_pulp/pull/5)

### CODE REVIEW

**Comment by mdellweg** [comment]
So this is quite a big architectural change. This does not mean it is bad, or we should not make it, but i need a little more thought about this. I thought, maybe we could go into a direction, where we have less code around managing the importing of python modules (that is the part i'm not really happy with).

**Comment by Timoses** [comment]
> I thought, maybe we could go into a direction, where we have less code around managing the importing of python modules (that is the part i'm not really happy with).

Which imports exactly are you referring to? Anyhow, take your time to think about it. It's worth it at this point, imo.

**Comment by mdellweg** [comment]
I am thinking of all those properties, that lazyload the apis which lazyload the client_bindings. This looks like a lot of code duplication, and i wanted to take a broader look at this, when a few modules are implemented, to see what can be reused and what cannot. So one way could be to take your solution and refactor from there.

**Comment by Timoses** [comment]
> I am thinking of all those properties, that lazyload the apis which lazyload the client_bindings. This looks like a lot of code duplication

Very true. I tried to follow that pattern since it seemed that at some points it was required to "translate" between the (self-written) API client and the actual pulp[core|-file]-client (as it was implemented already).
For example [here](https://github.com/mdellweg/ansible_modules_pulp/pull/7/files#diff-76c15490eb04ff33fae1ed1f12a910a8R62-R80) we don't just return the API but translate and eventually add more logic to make the API usage simpler from the client perspective.
So the indirection appears helpful.

All in all, I did not change much about the previous implementation other than cutting it into logical pieces and wrap them into classes (namely `PulpCoreApiClient`, `PulpFileApiClient` and `PulpEntityController`).

**Comment by Timoses** [comment]
Rebase to latest master
+ updated `RETURN` section in `pulp_file_*` modules to reflect change.

**Comment by Timoses** [comment]
This PR has become obsolete in the face of https://github.com/mdellweg/ansible_modules_pulp/pull/10

**Pull request closed without merging**
